name: Deploy Microservice
     on:
       push:
         branches:
           - main
     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v3
           - name: Configure AWS Credentials
            register_blue: true
             uses: aws-actions/configure-aws-credentials@v1
             with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-1
           - name: Login to Amazon ECR
             uses: aws-actions/amazon-ecr-login@v1
           - name: Build, tag, and push image to Amazon ECR
             run: |
               cd microservice
               docker build -t microservice:latest .
               docker tag microservice:latest ${{ secrets.ECR_REGISTRY }}/microservice:latest
               docker push ${{ secrets.ECR_REGISTRY }}/microservice:latest
           - name: Deploy to ECS
             run: |
               aws ecs update-service --cluster cloudzenia-ecs --service microservice-service --force-new-deployment
             env:
               AWS_REGION: ap-south-1
